// src/fontawesome.js
import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faUser,
  faTruck,
  faTools,
  faUserTie,
  faUserMinus,
  faEye,
  faTrash,
  faCog,
  faInbox,
  faTrashArrowUp,
  faCar,
  faComment,
  faHistory,
  faFileUpload,
  faUserPlus,
  faUserAltSlash,
  faFilePdf,
  faFileArchive,
  faCheck,
  faShareNodes,
  faClock,
  faRectangleList,
  faClose,
  faPencil,
} from "@fortawesome/free-solid-svg-icons";
import { faWhatsapp } from "@fortawesome/free-brands-svg-icons";

library.add(
  faUser,
  faTruck,
  faTools,
  faUserTie,
  faUserMinus,
  faEye,
  faTrash,
  faCog,
  faInbox,
  faTrashArrowUp,
  faCar,
  faComment,
  faHistory,
  faFileUpload,
  faUserPlus,
  faFilePdf,
  faUserAltSlash,
  faFileArchive,
  faCheck,
  faShareNodes,
  faClock,
  faWhatsapp,
  faRectangleList,
  faClose,
  faPencil
);
